export const invoiceData = [
    {
      labNo: "INV-001",
      patientName: "Tapas Das",
      date: "2024-05-10",
      tests: "Blood Test, X-Ray",
      entryNo: "A1",
      totalCost: "150",
      discount: "10",
      paid: "100",
      due: "40",
      paymentStatus: "Unpaid",
    },
    {
      labNo: "INV-002",
      patientName: "Janee Pal",
      date: "2024-05-12",
      tests: "MRI Scan",
      entryNo: "A2",
      totalCost: "300",
      discount: "20",
      paid: "50",
      due: "230",
      paymentStatus: "Unpaid",
    },
    {
      labNo: "INV-003",
      patientName: "Rahul Sen",
      date: "2024-05-14",
      tests: "CT Scan, Blood Test",
      entryNo: "A3",
      totalCost: "400",
      discount: "30",
      paid: "200",
      due: "170",
      paymentStatus: "Unpaid",
    },
    {
      labNo: "INV-004",
      patientName: "Meera Kaur",
      date: "2024-05-15",
      tests: "Ultrasound",
      entryNo: "A4",
      totalCost: "120",
      discount: "10",
      paid: "110",
      due: "0",
      paymentStatus: "Paid",
    },
    {
      labNo: "INV-005",
      patientName: "Amit Kumar",
      date: "2024-05-16",
      tests: "X-Ray, ECG",
      entryNo: "A5",
      totalCost: "180",
      discount: "15",
      paid: "100",
      due: "65",
      paymentStatus: "Unpaid",
    },
    {
      labNo: "INV-006",
      patientName: "Priya Sharma",
      date: "2024-05-18",
      tests: "Blood Test",
      entryNo: "A6",
      totalCost: "80",
      discount: "5",
      paid: "75",
      due: "0",
      paymentStatus: "Paid",
    },
    {
      labNo: "INV-007",
      patientName: "Vikram Mehta",
      date: "2024-05-20",
      tests: "MRI Scan, CT Scan",
      entryNo: "A7",
      totalCost: "600",
      discount: "50",
      paid: "400",
      due: "150",
      paymentStatus: "Unpaid",
    },
    {
      labNo: "INV-008",
      patientName: "Sonia Verma",
      date: "2024-05-22",
      tests: "X-Ray",
      entryNo: "A8",
      totalCost: "100",
      discount: "10",
      paid: "90",
      due: "0",
      paymentStatus: "Paid",
    },
    {
      labNo: "INV-009",
      patientName: "Arjun Gupta",
      date: "2024-05-25",
      tests: "Blood Test, Ultrasound",
      entryNo: "A9",
      totalCost: "220",
      discount: "20",
      paid: "150",
      due: "50",
      paymentStatus: "Unpaid",
    },
    {
      labNo: "INV-010",
      patientName: "Neha Kapoor",
      date: "2024-05-28",
      tests: "ECG, CT Scan",
      entryNo: "A10",
      totalCost: "350",
      discount: "25",
      paid: "200",
      due: "125",
      paymentStatus: "Unpaid",
    }
];
