export const testData = [
  {
    srNo: 1,
    testName: "PLEURAL FLUID",
    groupName: "PLEURAL FLUID/SYNOVI...",
    unit: "",
    normalRange: "",
    cost: "20.00",
  },
  {
    srNo: 2,
    testName: "P-LCR",
    groupName: "HAEMATOLOGY",
    unit: "%",
    normalRange: "13.0-43.0",
    cost: "0.00",
  },
  {
    srNo: 3,
    testName: "RDW-SD",
    groupName: "HAEMATOLOGY",
    unit: "fl",
    normalRange: "37.0-54.0",
    cost: "0.00",
  },
  {
    srNo: 4,
    testName: "STREEP FOR MP",
    groupName: "ARTHRITIS PROFILE",
    unit: "N",
    normalRange: "",
    cost: "250.00",
  },
  {
    srNo: 5,
    testName: "M.P(BY AG.CARD)",
    groupName: "HAEMATOLOGY",
    unit: "",
    normalRange: "",
    cost: "200.00",
  },
  {
    srNo: 6,
    testName: "PBF",
    groupName: "PBF",
    unit: "",
    normalRange: "",
    cost: "20.00",
  },
  {
    srNo: 7,
    testName: "TOTAL SPERM COUNT",
    groupName: "CHEMICAL EXAMINATION",
    unit: "Million/ML",
    normalRange: "60-150",
    cost: "0.00",
  },
  {
    srNo: 8,
    testName: "RDW-CV",
    groupName: "HAEMATOLOGY",
    unit: "%",
    normalRange: "11.0-16.0",
    cost: "0.00",
  },
  {
    srNo: 9,
    testName: "S.CALCIUM",
    groupName: "ELECTROLYTES TEST",
    unit: "MG/DL",
    normalRange: "8.4-10.4",
    cost: "10.00",
  },
  {
    srNo: 10,
    testName: "WIDAL TEST",
    groupName: "SEROLOGY",
    unit: "",
    normalRange: "",
    cost: "100.00",
  },
  {
    srNo: 11,
    testName: "CBC",
    groupName: "HAEMATOLOGY",
    unit: "",
    normalRange: "",
    cost: "50.00",
  },
  {
    srNo: 12,
    testName: "FBS",
    groupName: "BIOCHEMISTRY",
    unit: "MG/DL",
    normalRange: "70-100",
    cost: "30.00",
  },
  {
    srNo: 13,
    testName: "PPBS",
    groupName: "BIOCHEMISTRY",
    unit: "MG/DL",
    normalRange: "90-140",
    cost: "35.00",
  },
  {
    srNo: 14,
    testName: "LFT",
    groupName: "BIOCHEMISTRY",
    unit: "",
    normalRange: "",
    cost: "150.00",
  },
  {
    srNo: 15,
    testName: "KIDNEY FUNCTION TEST",
    groupName: "BIOCHEMISTRY",
    unit: "",
    normalRange: "",
    cost: "200.00",
  },
  {
    srNo: 16,
    testName: "TSH",
    groupName: "HORMONES",
    unit: "uIU/mL",
    normalRange: "0.3-5.0",
    cost: "70.00",
  },
  {
    srNo: 17,
    testName: "HBA1C",
    groupName: "BIOCHEMISTRY",
    unit: "%",
    normalRange: "4.0-6.0",
    cost: "90.00",
  },
  {
    srNo: 18,
    testName: "BLOOD UREA",
    groupName: "BIOCHEMISTRY",
    unit: "MG/DL",
    normalRange: "10-50",
    cost: "30.00",
  },
  {
    srNo: 19,
    testName: "SODIUM",
    groupName: "ELECTROLYTES",
    unit: "MEQ/L",
    normalRange: "135-145",
    cost: "25.00",
  },
  {
    srNo: 20,
    testName: "POTASSIUM",
    groupName: "ELECTROLYTES",
    unit: "MEQ/L",
    normalRange: "3.5-5.0",
    cost: "25.00",
  },
  {
    srNo: 21,
    testName: "HIV TEST",
    groupName: "SEROLOGY",
    unit: "",
    normalRange: "",
    cost: "500.00",
  },
  {
    srNo: 22,
    testName: "VDRL",
    groupName: "SEROLOGY",
    unit: "",
    normalRange: "",
    cost: "70.00",
  },
  {
    srNo: 23,
    testName: "DENGUE NS1",
    groupName: "SEROLOGY",
    unit: "",
    normalRange: "",
    cost: "300.00",
  },
  {
    srNo: 24,
    testName: "VITAMIN D",
    groupName: "BIOCHEMISTRY",
    unit: "NG/ML",
    normalRange: "20-50",
    cost: "700.00",
  },
  {
    srNo: 25,
    testName: "VITAMIN B12",
    groupName: "BIOCHEMISTRY",
    unit: "PG/ML",
    normalRange: "200-900",
    cost: "800.00",
  },
  {
    srNo: 26,
    testName: "THYROID PROFILE",
    groupName: "HORMONES",
    unit: "",
    normalRange: "",
    cost: "300.00",
  },
  {
    srNo: 27,
    testName: "RBS",
    groupName: "BIOCHEMISTRY",
    unit: "MG/DL",
    normalRange: "70-140",
    cost: "20.00",
  },
  {
    srNo: 28,
    testName: "URINE ROUTINE",
    groupName: "URINE EXAMINATION",
    unit: "",
    normalRange: "",
    cost: "40.00",
  },
  {
    srNo: 29,
    testName: "HCV",
    groupName: "SEROLOGY",
    unit: "",
    normalRange: "",
    cost: "400.00",
  },
  {
    srNo: 30,
    testName: "HBSAG",
    groupName: "SEROLOGY",
    unit: "",
    normalRange: "",
    cost: "350.00",
  },
  {
    srNo: 31,
    testName: "HEMOGLOBIN",
    groupName: "HAEMATOLOGY",
    unit: "G/DL",
    normalRange: "12-16",
    cost: "15.00",
  },
  // Add additional entries here, following the same structure
  ...Array.from({ length: 70 }, (_, i) => ({
    srNo: 32 + i,
    testName: `Test ${32 + i}`,
    groupName: `Group ${Math.ceil((32 + i) / 10)}`,
    unit: i % 2 === 0 ? "MG/DL" : "%",
    normalRange: i % 3 === 0 ? "10-50" : "",
    cost: (Math.random() * 500).toFixed(2),
  })),
];
